version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  app:
    build: .
    command: bash run_app.sh
#    volumes:
#      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_volume: