# Generated by Django 2.2.7 on 2020-04-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ID',
            field=models.IntegerField(unique=True),
        ),
    ]
